### ISSUE TITLE
does it preserve identity of the subject ?

### ISSUE THREAD

**Issue by 1blackbar** [Victarry/stable-dreambooth#1]
original inversion has a trouble with that, it  synhetsized mutations of the trained subjects unles you overfit and they you cant edit style anymore and composition that much.
Is it really like dreambooth and it retains identity ?

**Comment by Victarry** [comment]
Yes, it can preserve the identity of subject. But the quality of images still should be improved, and I will continue developing this project for better performance.

**Comment by 1blackbar** [comment]
whats the minimum ram requirement? will it run on 25GB colab ?

**Comment by Victarry** [comment]
In my experiment, the minimum RAM is about 30G.
