### ISSUE TITLE
Another implementation of DreamBooth for SD is available

### ISSUE THREAD

**Issue by morganavr** [Victarry/stable-dreambooth#2]
Maybe you guys should cooperate?

https://github.com/XavierXiao/Dreambooth-Stable-Diffusion

**Comment by Victarry** [comment]
Thanks for you advice and I will consider it.

The project of @XavierXiao is based on source code of [latent-diffusion](https://github.com/CompVis/latent-diffusion). My implementation is based on [Diffusers](https://github.com/huggingface/diffusers) and the source code is simpler.

**Comment by yuxu915** [comment]
> Thanks for you advice and I will consider it.
> 
> The project of @XavierXiao is based on source code of [latent-diffusion](https://github.com/CompVis/latent-diffusion). My implementation is based on [Diffusers](https://github.com/huggingface/diffusers) and the source code is simpler.

hi, could you please tell  differences between latent-diffusion based and diffusers based?
