### ISSUE TITLE
error when calling mode() on the vae encoded images

### ISSUE THREAD

**Issue by jhurlbut** [Victarry/stable-dreambooth#4]
Error is:
```
Traceback (most recent call last):
  File "train.py", line 206, in <module>
    train_loop(config, model, noise_scheduler, optimizer, train_dataloader)
  File "train.py", line 129, in train_loop
    latents = model.vae.encode(imgs).mode() * 0.18215
AttributeError: 'AutoencoderKLOutput' object has no attribute 'mode'
```

It seems related to the diffusers library not running on the gpu? I am in an environment with an a6000 though

**Comment by jhurlbut** [comment]
I think I fixed it by changing:
`latents = model.vae.encode(imgs).mode() * 0.18215`
to:
```
latents = vae.encode(imgs).latent_dist.sample().detach()
latents = latents * 0.18215
```
but am now getting CUDA out of memory error:
`RuntimeError: CUDA out of memory. Tried to allocate 4.00 GiB (GPU 0; 47.54 GiB total capacity; 30.76 GiB already allocated; 1.22 GiB free; 33.29 GiB reserved in total by PyTorch)`

**Comment by Victarry** [comment]
Thanks for your advice. The first error is due to the version upgrade of `diffusers`. I will fix this soon.

You can change the batch_size to `2` in TrainConfig to solve to OOM problem.

**Comment by Victarry** [comment]
Fixed.
